image: hadolint/hadolint:latest-debian

stages:
  - lint

lint 8:
  stage: lint
  script:
    - hadolint 8/Dockerfile

lint 11:
  stage: lint
  script:
    - hadolint 11/Dockerfile

lint 8 slim:
  stage: lint
  script:
    - hadolint 8/slim/Dockerfile

lint 11 slim:
  stage: lint
  script:
    - hadolint 11/slim/Dockerfile

lint 8 alpine:
  stage: lint
  script:
    - hadolint 8/alpine/Dockerfile

lint 11 alpine:
  stage: lint
  script:
    - hadolint 11/alpine/Dockerfile
